parser: babel-eslint
env:
    es6: true
    browser: true
    node: true
parserOptions:
    ecmaVersion: 6
    ecmaFeatures:
        experimentalObjectRestSpread: true
        jsx: true
    sourceType: module
globals:
    atom: true
plugins:
    - react
    - import
extends:
    - plugin:react/recommended
    - plugin:import/errors
    - plugin:import/warnings
settings:
    import/core-modules: [atom, remote]
rules:
    array-bracket-spacing: [error, never]
    arrow-parens: [error, as-needed]
    eol-last: 0
    jsx-quotes: [error, prefer-single]
    new-cap: 0
    no-debugger: 1
    no-undef: 2
    no-underscore-dangle: 0
    no-unused-vars: [error, {vars: all, args: none, varsIgnorePattern: _+}]
    no-use-before-define: 0
    object-curly-spacing:  [error, never]
    quotes: [error, single, {avoidEscape: true, allowTemplateLiterals: true}]
    semi: [error, never]
    strict: 0
    import/no-named-as-default-member: 0
    react/jsx-boolean-value: 0
    react/jsx-no-undef: error
    react/jsx-uses-react: 1
    react/jsx-uses-vars: 1
    react/no-did-mount-set-state: 0
    react/no-did-update-set-state: 2
    # only 1 stateful component (class)
    react/no-multi-comp: [error, ignoreStateless: true]
    react/no-unknown-property: 1
    react/prop-types: [error, {ignore: [children]}]
    react/self-closing-comp: 1
