#!/usr/bin/env bash

# apm publish [<newversion> | major | minor | patch | build]
if [[ $# -eq 0 ]]; then
    kind="patch"
else
    kind="$1"
fi


# echo "Now, publish to atom.io? (ctrl-c for exit)"
# read var
apm publish $kind


# generate CHANGELOG.md
github_changelog_generator
git commit -a -m "Updated changelog"
git push
